services:
  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: password # I swear if you use this in production...
    ports:
      - "5432:5432"